image: Visual Studio 2017

before_build:
  - nuget restore Vivid.sln

configuration:
  # - Debug
  - Release

build:
  project: Vivid.sln

# before_test:
#   - docker version
#   - pip install docker-compose
#   - docker-compose version

# test_script:
#   - cd test/Ops.IntegrationTests/
#   - docker-compose up -d
#   - dotnet test --no-build --configuration Release

test: off
