dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Buid Docker images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        - secure: ezT09UzTu6ZryUiLCUipZPkvRTZfNuUEOxPdBMbkGwfeFgeSLJtJCSp+udFBxg7NCnq9bAFP16YcBrOl3gzps5SVY2bwx8FOPQ44owpj+Wjbw85b6pJXAZ21KpxVorg0YrcpC1ycNVFg8iZAIFz7c2/JPkpWQEsrr6qVSfetjkaLub8+KdHZnalnRGj3DEbsamfT+VUlFwygjoWj9hbh8Utn9oG6svcWEN4YOJ4rAxIvpcAXWyN2dn97mv4c14Maqr3FCKtCWfLioAP0NLiF9R9KK4Eao5v/cNdAgqeainoO3i22E/6n2XgurBBDnE8uMMkF6TnUPRvMKGzj7DiC60fcEAb3+oV29tIFZc4JJ5caoUIXwFPMgh2xSLwkWIslrBv1wfRCgYcziyBav4WTGrs3jDBuihQpcY18VeYyRJ6tD31NiOFedoKnIoEsocrCnR08ce8wE/mJNfi3b7NpX4RNowwXfWvJ/H8K4PI1279LhTWXdhDzCGj23o/cThBzqXPq2L+YJBDhf7+kH82Xj7MTQtwlGbbGNK3aGeoSEQy9IKvRYwB3yozufJj1CaLFz9FwzgNBz/WXWu3H428QXLKCFfcp+0BQhLxAnnQu1pewuxfxtUAMVaJX3VtUKXUXZr1uROvY9WY3sHHvyGTXnW5IlHAmoii7+lkj30q/kpU=
    - stage: Test
      name: "Vivid tests"
      install: cd scripts && npm ci && cd ..
      script: echo ToDo
    - name: "Vivid Operations - Systems Integration Tests"
      install:
        - cd scripts && npm ci && cd ..
        - docker pull zevere/botops-vivid:unstable-solution
      env:
        - image_tag=zevere/botops-vivid:unstable-solution
      script: node scripts/test/ops.integration.test.js
    - stage: Deploy
      name: "Deploy"
      script: skip
      env:
        - image_tag=zevere/botops-vivid:unstable
        - secure: kVv/QuTMJa3pscI2OBx3OMtIPUWFi60q3yS4MPa5Q2zUZYeRNx5ac8pj0pa8NS8qVHiVOgOafsYzhOSj0dj1xdNXkk2+WKLgKxzS+QJMABSr4qTwheAvGW77VEemxD5oviivZj5/2VDg8y8ZVAjn9TajSuRXmjoHUAuwJJZZtiFdA0rGF38DhtZm6wu73sU007a2I2EQp6j0qbJZQvmJ417vbqvbsu3rEtgU3my/PvkMXXI/91EM1xDmPvkD2HOGx5NH1uE3y3dBJvjAJjGEXTRga/ExtjZecMitW3SZXjPuHrj+09Kf2kBIo2ZN++2jXmgSdgpiffPCedgNl+dZeL9ZNg4rQXtmlPq9MHx2kQL1SH4Sr1qAFwICfMBEi/tumgJ/nPK6nuTPqULbLNAcj+xoooobqYNaQJ8mK3B6LpwPsaw/TQ1d7iH3xWVsThSxN+E17jdJA3bOytsTTK7vXq2HLdhBm0FeKGi+HVC/Yg43s3br/2B0+3pc/epjHYpxyxqp1p2HOkDL25DJtU3Rwk6SFQE4q//pujvWZ+jTIfpXGqzY0XNqkqdCcOCaXuQ6S/VNwGo0lQYWKERala2Zs6CyrViAjt8rkNoHJdKqoKEhiiV7Qjvc7YuqAw9yvrTqXHM6B2kUL4hsvK51ruErgmMPIU9wkJ3mPlELDXV0brk=
      install: cd scripts && npm ci && cd ..
      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Staging
          on:
            branch: develop
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master
    - stage: PIV
      name: "PIV Checks"
      script: echo ToDo


# env:
  # DEPLOY_SETTINGS_JSON='{"Staging":[ /* ... */ ]}'
  # - secure: CcNQ3mQ4QPnOvAIt1rCoOrt9jVYpsRXDIyAAdsnQi4DAEK0Zycge7yJSAv/YbDQTCwSS8KzNsX+OxegH7WpGkfkEQI76WKkgMEFwURscFsk8pDb+wQj5J3tINtZi9wOOe8yL7IHRYtYln2rMNG9qsaKBLC/dVpLwSDuOG6itk2ScqArOl8MVEDWJH5b2I8GY0kiUAaUWRjY3HhsKOuOb+fiMttrTr6K+tfa+RbW9T5exT2c1K0oTRC0yTpSSgymJn0vcnTB19awdMcxh3Gpey73Hz/hd+41gK9E1/xiGGimlpwWdDV3fPkHYRDmYOR7YkfD4Qtn1MO/r8K1AdIouRTpsZ2FCt7PTH4mBxHPzRNri6gITGbjiNCaUj+csjjDND14wvg1g+jTWA/5I7u8moDmiOczIXKjPKtmqNDMzFCDQXbx4zKvdf0j6UNmLeBQ8+TkQfba7b9dCtPAIQbaw8hPOSzZ8wKC8A3yvaSSrtOIvQ3qK5p8n+FxAgeeoHicPj68jhG4oSPh9R+pyy1n+5RmUtESV7KIB1d2coQJ8oBcfI16VX6oif8XWObkFxn/TQca37Mh4Y27Gaz0+S2VUZWTqZOHgTmyAyMB7DFmqfJx3X0jEADfrjQRJ46zQ2LwW3QHmPa0sZkHKtHx/p7Gc7uoIIG+L16jHFRzA9tj8yY8=


# Disable "Build pushed pull requests"

# env:
#   DEPLOY_SETTINGS_JSON: A mapping of environment to the deployment types and their options.
#   {
#     "Staging": [
#       { "type": "docker",
#         "options": { "source": "foo:edge", "target": "foo/bar:latest", "user": "foo", "pass": "PASS" }
#       },
#       { "type": "heroku",
#         "options": {
#           "app": "foo-staging", "source": "foo:latest", "dyno": "web", "user": "foo@example.org", "token": "TOKEN"
#         }
#       }
#     ],
#     "Production": [ ]
#   }
