dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Buid Docker images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        - secure: Ch9AhTI/xhU7ybxZDkMF1w6Eh6eQSlz6T+nMrK8pqqnPGxbphTK+D2HmDeGxBVClDB5homlrvG1/LkMAZgHfbYOaY36hEhj891Ec/l5RS+parg2C7cKYwqhJqnR3jgTN/x7uiP6JSdf9/6Y52MpfEmhWx6Sf9XoPSZGwHHDY+V5jCEA8kmpgwJs4v5B28x59JgKbQDd/1O8UDC3U1tFKqfG5WU0XyIeenMAoBqXCahYndJ+4UZGSwl25EkP6koumhl6iAImlHDS03eyzPzXl4xzWj37791jGxbaVPhaTC8m66w4nJImxoMOBfN9jTfEC0apduF+NW4kZ0dK+7nVeta4xIGj/p3taDrePdRAy8J4ASoak9l8/42Cu7ejKHgFmqhgVSOMYsM5qV+vjrSgK0Sm53t5SMd0oU9FBDQdByFdTZpYonBHhLAFqDG4/eABRBs2vQQZOvr/rcK/dE6tw6+OtC/uMHaEb64qXoQa3au3jvvYSyy61RGSeV9CQvn1VhqhtmMHdYvXZcwus2ua4/JwVpn134gMWH4NPe0XcLfQa7pf3lx9iM316Uold89h5pRvowRxgh6k/DetZriQTWeoYKFkF9FWMqVb3VSeKyo5z86KcX8AX2fa1Es/driUtpl3qOXzjug1zTq645DxJ9yHCsyrRGcZShkvUOeRev38=
    - stage: Test
      name: "Vivid tests"
      install: cd scripts && npm ci && cd ..
      script: echo ToDo
    - name: "Vivid Operations - Systems Integration Tests"
      install:
        - cd scripts && npm ci && cd ..
        - docker pull zevere/botops-vivid:unstable-solution
      env:
        - image_tag=zevere/botops-vivid:unstable-solution
      script: node scripts/test/ops.integration.test.js
    - stage: Deploy
      name: "Deploy"
      script: skip
      env:
        - image_tag=zevere/botops-vivid:unstable
        - secure: Ch9AhTI/xhU7ybxZDkMF1w6Eh6eQSlz6T+nMrK8pqqnPGxbphTK+D2HmDeGxBVClDB5homlrvG1/LkMAZgHfbYOaY36hEhj891Ec/l5RS+parg2C7cKYwqhJqnR3jgTN/x7uiP6JSdf9/6Y52MpfEmhWx6Sf9XoPSZGwHHDY+V5jCEA8kmpgwJs4v5B28x59JgKbQDd/1O8UDC3U1tFKqfG5WU0XyIeenMAoBqXCahYndJ+4UZGSwl25EkP6koumhl6iAImlHDS03eyzPzXl4xzWj37791jGxbaVPhaTC8m66w4nJImxoMOBfN9jTfEC0apduF+NW4kZ0dK+7nVeta4xIGj/p3taDrePdRAy8J4ASoak9l8/42Cu7ejKHgFmqhgVSOMYsM5qV+vjrSgK0Sm53t5SMd0oU9FBDQdByFdTZpYonBHhLAFqDG4/eABRBs2vQQZOvr/rcK/dE6tw6+OtC/uMHaEb64qXoQa3au3jvvYSyy61RGSeV9CQvn1VhqhtmMHdYvXZcwus2ua4/JwVpn134gMWH4NPe0XcLfQa7pf3lx9iM316Uold89h5pRvowRxgh6k/DetZriQTWeoYKFkF9FWMqVb3VSeKyo5z86KcX8AX2fa1Es/driUtpl3qOXzjug1zTq645DxJ9yHCsyrRGcZShkvUOeRev38=
      install: cd scripts && npm ci && cd ..
      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Staging
          on:
            branch: develop
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master
    - stage: PIV
      name: "PIV Checks"
      script: echo ToDo


# env:
  # DEPLOY_SETTINGS_JSON='{"Staging":[ /* ... */ ]}'
  # - secure: CcNQ3mQ4QPnOvAIt1rCoOrt9jVYpsRXDIyAAdsnQi4DAEK0Zycge7yJSAv/YbDQTCwSS8KzNsX+OxegH7WpGkfkEQI76WKkgMEFwURscFsk8pDb+wQj5J3tINtZi9wOOe8yL7IHRYtYln2rMNG9qsaKBLC/dVpLwSDuOG6itk2ScqArOl8MVEDWJH5b2I8GY0kiUAaUWRjY3HhsKOuOb+fiMttrTr6K+tfa+RbW9T5exT2c1K0oTRC0yTpSSgymJn0vcnTB19awdMcxh3Gpey73Hz/hd+41gK9E1/xiGGimlpwWdDV3fPkHYRDmYOR7YkfD4Qtn1MO/r8K1AdIouRTpsZ2FCt7PTH4mBxHPzRNri6gITGbjiNCaUj+csjjDND14wvg1g+jTWA/5I7u8moDmiOczIXKjPKtmqNDMzFCDQXbx4zKvdf0j6UNmLeBQ8+TkQfba7b9dCtPAIQbaw8hPOSzZ8wKC8A3yvaSSrtOIvQ3qK5p8n+FxAgeeoHicPj68jhG4oSPh9R+pyy1n+5RmUtESV7KIB1d2coQJ8oBcfI16VX6oif8XWObkFxn/TQca37Mh4Y27Gaz0+S2VUZWTqZOHgTmyAyMB7DFmqfJx3X0jEADfrjQRJ46zQ2LwW3QHmPa0sZkHKtHx/p7Gc7uoIIG+L16jHFRzA9tj8yY8=


# Disable "Build pushed pull requests"

# env:
#   DEPLOY_SETTINGS_JSON: A mapping of environment to the deployment types and their options.
#   {
#     "Staging": [
#       { "type": "docker",
#         "options": { "source": "foo:edge", "target": "foo/bar:latest", "user": "foo", "pass": "PASS" }
#       },
#       { "type": "heroku",
#         "options": {
#           "app": "foo-staging", "source": "foo:latest", "dyno": "web", "user": "foo@example.org", "token": "TOKEN"
#         }
#       }
#     ],
#     "Production": [ ]
#   }
