dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Buid Docker images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: ezT09UzTu6ZryUiLCUipZPkvRTZfNuUEOxPdBMbkGwfeFgeSLJtJCSp+udFBxg7NCnq9bAFP16YcBrOl3gzps5SVY2bwx8FOPQ44owpj+Wjbw85b6pJXAZ21KpxVorg0YrcpC1ycNVFg8iZAIFz7c2/JPkpWQEsrr6qVSfetjkaLub8+KdHZnalnRGj3DEbsamfT+VUlFwygjoWj9hbh8Utn9oG6svcWEN4YOJ4rAxIvpcAXWyN2dn97mv4c14Maqr3FCKtCWfLioAP0NLiF9R9KK4Eao5v/cNdAgqeainoO3i22E/6n2XgurBBDnE8uMMkF6TnUPRvMKGzj7DiC60fcEAb3+oV29tIFZc4JJ5caoUIXwFPMgh2xSLwkWIslrBv1wfRCgYcziyBav4WTGrs3jDBuihQpcY18VeYyRJ6tD31NiOFedoKnIoEsocrCnR08ce8wE/mJNfi3b7NpX4RNowwXfWvJ/H8K4PI1279LhTWXdhDzCGj23o/cThBzqXPq2L+YJBDhf7+kH82Xj7MTQtwlGbbGNK3aGeoSEQy9IKvRYwB3yozufJj1CaLFz9FwzgNBz/WXWu3H428QXLKCFfcp+0BQhLxAnnQu1pewuxfxtUAMVaJX3VtUKXUXZr1uROvY9WY3sHHvyGTXnW5IlHAmoii7+lkj30q/kpU=
    - stage: Test
      name: "Vivid tests"
      install: cd scripts && npm ci && cd ..
      script: echo ToDo
    - name: "Vivid Operations - Systems Integration Tests"
      install:
        - cd scripts && npm ci && cd ..
        - docker pull zevere/botops-vivid:unstable-solution
      env:
        - image_tag=zevere/botops-vivid:unstable-solution
      script: node scripts/test/ops.integration.test.js
    - stage: Deploy
      name: "Deploy"
      branches:
        only:
          - develop
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull zevere/botops-vivid:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Staging":[
        #   {"type":"docker","options":{"source":"zevere/botops-vivid:unstable","target":"zevere/botops-vivid:edge","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"zv-s-botops-vivid","source":"zevere/botops-vivid:edge","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: ZvcauqdSpS+g3706oT0CuVurvLBERvr5f8dGEKS3BKaNNQmlLaPqIz7Bok2GPQRkApnmerBLwA39zXaNAITpT61ZgRNtUpbWGpK9Wg+bUkPTvwZfubsqel7Lzg5HpBcA7f4bZl1gtJ2weYwXPNSPusijaxYqAoq/XN3YsawW2BfhTKDXWkMQo1cJbolTzbUTqMVfV3Rj8/0amgoOyxvYSadqlWPRhs8mk0yiszMq0hKbQtM8a5jnMyBin2P+mc93EMwL0+2GxCyWGvmwHQHftKS/fSO5DzSnzkonQkBXkSoeahdASkdOItWITXaP+HjO0HzGKEntnjBC+hPG5kbr3IGesSClzDleB2DldHdjFkh9zKTNNpf9xTiUjPLus5BfldaCr7agDK6KGvc3TxJwwnxXjXaq9h2uQokdXwK0bQkh2WtR01JVLKZsBcMPRKYEQo5Aqu8Y7doZFNfPdAqiWtSvbCyrI1Fr7FjxwbAV05GzWGUqnYVQ0egZYgjh1MoMaWCeDORN57nEq/3YeZnJAnh4JC/WFrQTsaPdX074aNRwj+Gf6w4lJG28QvGCt36Qr8KQLOViPb8V/l1ouTcYzrwRAECzPt4xRxZ9sMSoi5t4a5exRPb4ESizrLrpXMRRgEZsvUgXMZjhh0gdiFZmOYz03fYU8GE2AFfc/JSDU78=
      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Staging
          on:
            branch: develop
    - stage: PIV
      name: "PIV Checks"
      branches:
        only:
          - master
          - develop
      script: echo ToDo

# Disable "Build pushed pull requests"
